### ISSUE TITLE
No 'Mod settings' at hangar & simple mods_marksOnGunExtended

### ISSUE THREAD

**Issue by schidakov** [spoter/spoter-mods#12]
mods_marksOnGunExtended doesn't show a '_Mod settings_' button at the hangar.
Also, during action, it shows only simple progress data, there is only one digit.
This problem issues alongside with Protanki modpack & with a clean WoT install.

Sorry, I do not currenlty have an in-game screenshot, but attach a hangar one:
![shot_015](https://user-images.githubusercontent.com/1462223/41349758-9a350388-6f19-11e8-85e8-f5a9591b1181.jpg)

Please, fix it

**Comment by sharewax** [comment]
Plus one for this issue - the same error - no setting and only simple progress in game.

**Comment by spoter** [comment]
Press ESC in hangar. Settings button moved in this menu.

**Comment by schidakov** [comment]
Found. Thank you

**Comment by sharewax** [comment]
Found. But it's too small to find :D Thanx!
