### ISSUE TITLE
mod_crewExtended _ format-error in (sub-)crewpanel

### ISSUE THREAD

**Issue by elektrosmoker** [spoter/spoter-mods#24]
it´s a minor thing, but as you can see on the attached picture there is an error in displaying the correct value ( it´s also showing the code).

![shot_089](https://user-images.githubusercontent.com/40739360/50575334-e9170e00-0dfd-11e9-80e8-cb556165954d.jpg)

**Comment by spoter** [comment]
I know, this issue with WG flash.
Last 4 year not fixed.
