### ISSUE TITLE
Request for permission to use your mods_mod_gui for my own mod

### ISSUE THREAD

**Issue by Paxifixi** [spoter/spoter-mods#27]
Hello spoter,

i couldn't find a direct email to get in contact with you, so i will write it here.

I'm a WoT mod developer and want to ask you for permission to include your mod_mods_gui in my mod-package to allow the players to easily enter a settings dialog to control the mod options.

I saw so many mods with no GUI for it, where people need to enter the json-config-textfile and i want to avoid this. 

In my eyes there should be one config standard for all mods, and i really like your solution for it.

Can i use it for my mod too and put the needed mod_mods_gui_2.16.wotmod and gambiter.guiflash_0.2.5.1.wotmod in my mod package? Of course you will get the credits for it!

Any feedback would be great.

thanks in advance

**Comment by spoter** [comment]
Sure, no problem.
Ty
