### ISSUE TITLE
cycling thru the predefined configs never show up 'config' setting again.

### ISSUE THREAD

**Issue by Paxifixi** [spoter/spoter-mods#29]
marksOnGunExtended v6.03

cycling (with ALT-NUMPAD 9 by default) thru the UI (predefined configs) never show up the 'config' setting again.

Is it possible that the problem is here at line: 907 ?
config.data['UI'] = 1

should it be set back to 0 ? because after 'UIReplayColorDamage' it restarts the rotation with 'UI_menu_UIskill4ltu' and not with 'UI_menu_UIConfig'

regards

**Comment by spoter** [comment]
select in hangar setting. 
special remove custom config in rotation. if error in config may get tonnz isues.

**Comment by Paxifixi** [comment]
ok, i understand. but it's already shown at the beginning of the rotation when it was selected in the hangar, or? :) 

how about a check of valid entries when the config is loaded? or a min/max setting for values in the config class? exactly its defined for a slider.

just an idea... keep on your good work!

**Comment by spoter** [comment]
I think,  if you create good visual style and test it on configuration section, send it to me, I'm add in default configuration rotation with you name and credits.
Ty.

**Comment by Paxifixi** [comment]
okay, i will try it out in the upcoming days. 

thank you
