### ISSUE TITLE
background to small for "play more" text.

### ISSUE THREAD

**Issue by Paxifixi** [spoter/spoter-mods#30]
Sometime MoE has not enough data to display the needed values.

in calcBattlePercents you replace the missing values with set config.i18n['NaN'], which shows the  "play more" info.

when this happens some of the predefined background sizes are too small. It works fine when the values are there, but not with the NaN replacement-text.

if you need more infos or a screenshot feel free to drop me a line.

**Comment by spoter** [comment]
Oh, try fix in next version. Thx

**Comment by spoter** [comment]
returned NaN

**Comment by Paxifixi** [comment]
It returns NaN, right, and NaN will be replaced with the specified translation for it. i my case with "play more". And this text still doesnt fit into the background. The total text goes over the right side of the background.
