### ISSUE TITLE
mod_mods_gui no longer supports language files?

### ISSUE THREAD

**Issue by Paxifixi** [spoter/spoter-mods#31]
Hi Spoter,

you know, i love your mods and i using the mod_mods_gui also for my own gui settings. In the past the mods_gui accepted language files but it seems that in the current version it ignores it. regardless which game client language i choose in wot it always shows everything in english.

can you take a look on it please? it was working fine in 2.15

my current mod_mods_gui  version: 2.17

any feedback would be great

**Comment by Paxifixi** [comment]
my fault. now it works.

but the main button from the ESC menu in the hangar is not translated, right?

**Comment by Paxifixi** [comment]
![ESCmenu](https://user-images.githubusercontent.com/4185209/54764563-574ac000-4bf8-11e9-9e93-743059f54f1e.png)
You closed the issue but i still need to know if the main button in the ESC menu can be translated in the language files? If not, can you make it so thats included in the config.i18n ?

**Comment by spoter** [comment]
oh sorry. im done it in mods_gui 2.19 and forgot publish it...
so sorry.

**Comment by Paxifixi** [comment]
It works perfect! Thank you
