### ISSUE TITLE
Insignia Monitor - no settings menu with mod_mods_gui_2.17

### ISSUE THREAD

**Issue by Paxifixi** [spoter/spoter-mods#32]
Hi spoter,

when i try to use your new insignia monitor mod i see no settings menu. It only shows the UI_aim frame

do you maybe use another mods_gui version?

![settings_insignia](https://user-images.githubusercontent.com/4185209/54495080-f44be700-48e0-11e9-8c99-fe85fa9ecaf9.png)

**Comment by spoter** [comment]
this is beta version mod.
im not ready to create settings. work on engine and battle UI now

**Comment by Paxifixi** [comment]
oh, sorry. i only noticed v1.00 and installed it.
