### ISSUE TITLE
MoE doesn't show correct marks in Tech Tree.

### ISSUE THREAD

**Issue by sharewax** [spoter/spoter-mods#33]
As you can see, it's only some settings for "font size".
<img width="544" alt="image" src="https://user-images.githubusercontent.com/9673243/54668879-0906c580-4b01-11e9-86ff-8aa76fa850bd.png">

**Comment by spoter** [comment]
Thats old version.
WG delete html in Tech tree.

**Comment by sharewax** [comment]
Sorry, my fault, forget to update main mods dir :)
