### ISSUE TITLE
mod_mods_gui: list of all available methods for developer?

### ISSUE THREAD

**Issue by Paxifixi** [spoter/spoter-mods#38]
Hi spoter,

as you know i use your mods_gui for my mods too and i really like it. Unfortunately you didn't share the source of this masterpiece of code, so i want to ask if it's possible to send me a list of all available methods of it?

The only reference i have are your other public mods, but it would be nice to know how many other useful functions are there .

Do you can help in this case?

**Comment by spoter** [comment]
LOG(arg, *args)
LOG_NOTE(*args)
LOG_ERROR(*args)
LOG_DEBUG(*args)
@inject.log
@inject.hook
@inject.hook_static 
inject.message(message, color='#FFD700', type='PlayerMessages') #VehicleMessages, VehicleErrorMessages, PlayerMessages
inject.createTexture(color, filename) #in 'objects/textures/' on res_mods
inject.createFont(filename, face, size, bold=False, dropShadow=True, shadowAlpha=128) #in 'system/fonts/' on res_mods
inject.convertColor(color) 
bool inject.ru 

g_data.register_data(name, dict_data)
g_data.register_json(name, dict_data, author, configPath)
g_data.register_lang(name, dict_data, author, configPath)
g_data.get_data(name)
g_data.get_json(name)
g_data.get_lang(name)
g_data.update_data(name, dict_data)
g_data.update_json(name, dict_data, author, configPath)

g_gui.register(name, template_func, settings_dict, apply_func)
g_gui.update(name, template_func)
g_gui.register_data(name, settings_dict, i18n, author='', configPath='./mods/configs')
g_gui.update_data(name, settings_dict, author='', configPath='./mods/configs')
g_gui.get_key(keys)

browser.open(link, internal=True)
COMPONENT_TYPE 
COMPONENT_ALIGN 
COMPONENT_EVENT 
g_guiFlash

**Comment by Paxifixi** [comment]
perfect, thank you
