### ISSUE TITLE
Incorrect Calculations 

### ISSUE THREAD

**Issue by falconeer40** [spoter/spoter-mods#39]
For whatever reason using MoE in regards to my type 59 yields poor results, according to the mod my average is around 1300 combined average, whereas if you check several stat sites, my DPG is 1550+ alone, in addition my moe % is currently at 71% in game, which would never be possible with that combined damage. I believe that the mod is taking in to account too many games, as many of my games were very poor prior to the last 100.

**Comment by spoter** [comment]
Play 3 game today, all data will be regenerated and recalculated.
Its dynamic values.
