### ISSUE TITLE
MoE suggestion: showing the gun mark percentage in the hangar

### ISSUE THREAD

**Issue by CH4MPi** [spoter/spoter-mods#42]
How about an option to show the current currentMovingAvgDamage in the hangar?

like this:
![image](https://user-images.githubusercontent.com/4185209/55666062-3c5b8b00-5849-11e9-8b52-971c7e4365ce.png)

this would help to avoid to click every time through the menues (stats - techtree etc.) to see the last known percentage of the gun mark

**Comment by spoter** [comment]
interested idea, i try do that

**Comment by spoter** [comment]
Done

**Comment by CH4MPi** [comment]
excellent work! Thanks :)
