### ISSUE TITLE
mod_mods_gui

### ISSUE THREAD

**Issue by hatsnal** [spoter/spoter-mods#44]
mod_mods_gui по-ходу не работает. Ставил на последнюю версию клиента, ииии кнопки настройки модов нету, может есть какой нибудь фикс ?

**Comment by spoter** [comment]
В ангаре нажал ESC и кнопки модов не появилось? Версия клиента 1.5 чтоли? Там его ещё не смотрел.

**Comment by hatsnal** [comment]
Да, все норм. Почитал закрытые issue, спасибо :)
