### ISSUE TITLE
mods_mods gui question

### ISSUE THREAD

**Issue by Arkhorse** [spoter/spoter-mods#50]
Hi spoter! im currently making my first script mod and I want to use your mod for settings. How do I do that? Ive looked at your mods, and and written some code based on that, but it doesnt seem to work. Please let me know how, thanks :)

This is my repo for this mod: https://github.com/Arkhorse/wot-Camo-Mod

Currently just want to get the settings working first.

**Comment by spoter** [comment]
you forget init 
config = Config()

**Comment by Arkhorse** [comment]
Yeah, I added it, and alot of the other stuff locally. However, until the mod is finished, Im going to just remove that but for now. 

But, could you help me a bit? I think I got it working, but not sure. Just pushed my most up to date version. Can you see anything that might make it not work?
