### ISSUE TITLE
Автор! Напиши пж в телегу Alinktothelast. Вопросы по коду

### ISSUE THREAD

**Issue by HASKADOG** [spoter/spoter-mods#67]

**Comment by spoter** [comment]
в карету может ещё написать? не знаю что такое телега.

**Comment by HASKADOG** [comment]
> в карету может ещё написать? не знаю что такое телега.

Прости(. Телеграм имел в виду. Я хочу написать свой мод, читаю твой кож но есть общие вопросы по строению клиента, все что есть в инете от 2014 года( Напиши, пожалуйста свой телеграмм, или как тебе удобно связаться

**Comment by spoter** [comment]
пиши в Скайп spoter82, телеграмм это какая-то новомодная фигня, ни разу не пользовался.

**Comment by HASKADOG** [comment]
> пиши в Скайп spoter82, телеграмм это какая-то новомодная фигня, ни разу не пользовался.
Не ищет(

Предлагает по ссылке пригласить. https://join.skype.com/invite/lugAag8Suf44

**Comment by HASKADOG** [comment]
> пиши в Скайп spoter82, телеграмм это какая-то новомодная фигня, ни разу не пользовался.

![image](https://user-images.githubusercontent.com/27897422/96335085-72a0da00-107e-11eb-9f5b-5210360b8768.png)
